name: Google Docs Sync to GitHub

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Sync Google Docs to GitHub
        env:
          GOOGLE_CLIENT_ID: ${{ secrets.GCI }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GCS }}
          DOCUMENT_ID: ${{ secrets.DID }}
        run: |
          python3 sync_docs.py

      - name: Commit and Push Changes
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add synced_docs/document.html || exit 1
          git commit -m "Updated synced Google Doc" || echo "Nothing to commit"
          git push || echo "Nothing to push, already up to date"
